env:
  CIRRUS_CLONE_DEPTH: 0
  BUILD_REPOSITORY_NAME: $CIRRUS_REPO_FULL_NAME
  SYSTEM_PULLREQUEST_SOURCEBRANCH: $CIRRUS_BRANCH
  SYSTEM_PULLREQUEST_PULLREQUESTID: $CIRRUS_PR
  BUILD_SOURCEVERSION: $CIRRUS_CHANGE_IN_REPO
  BUILD_SOURCEBRANCHNAME: $CIRRUS_BRANCH
macos_task:
  matrix:
    - python_version: "3.11"
    - name : Cirrus MacOS Universal2
      macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-xcode:14
    
      mac_script:
        - |
          cd compile_scripts &&
          bash compile-mac-universal2.sh &&
          cd .. &&
          cd dist &&
          ln -s /Applications "Applications" &&
          hdiutil create -fs HFS+ -srcfolder . -volname "Toontown Rewritten Custom Launcher" "Toontown Rewritten Custom Launcher.dmg" &&
          cd .. &&
          mkdir artifacts &&
          mv dist/Toontown\ Rewritten\ Custom\ Launcher.dmg artifacts/Toontown\ Rewritten\ Custom\ Launcher.dmg

  env:
    BUILD_ARTIFACTSTAGINGDIRECTORY: ${CIRRUS_WORKING_DIR}/artifacts
    ARTDIR: ${CIRRUS_WORKING_DIR}/artifacts/
    CI_HAS_ARTIFACTS: true
  artifacts:
    name: Artifact
    path: "artifacts/*"

  windows_task:
    matrix:
      - python_version: "3.11"
      - name : Cirrus Windows
        windows_instance:
          image: cirrusci/windowsservercore:visualstudio2019
          cpu: 8
          memory: 16G
        windows_script:
          - |
            python3 -m pip install -r requirements.txt pyinstaller pillow &&
            cd compile_scripts &&
            ./compile.bat &&
            cd .. &&
            mkdir artifacts &&
            mv dist/Toontown\ Rewritten\ Custom\ Launcher.exe artifacts/Toontown\ Rewritten\ Custom\ Launcher.exe
    env:
      BUILD_ARTIFACTSTAGINGDIRECTORY: ${CIRRUS_WORKING_DIR}/artifacts
      ARTDIR: ${CIRRUS_WORKING_DIR}/artifacts/
      CI_HAS_ARTIFACTS: true
    artifacts:
      name: Artifact
      path: "artifacts/*"
    linux_task:
      matrix:
        - python_version: "3.11"
        - name : Cirrus Linux
      container:
        image: rpcs3/rpcs3-ci-bionic:1.8
        cpu: 4
        memory: 16G
      linux_script:
        - |
          cd compile_scripts &&
          bash compile-linux.sh &&
          cd .. &&
          cd dist &&
          zip -r "Toontown Rewritten Custom Launcher-Linux.zip" "Toontown Rewritten Custom Launcher" &&
          cd .. &&
          mkdir artifacts &&
          mv dist/Toontown\ Rewritten\ Custom\ Launcher-Linux.zip artifacts/Toontown\ Rewritten\ Custom\ Launcher-Linux.zip
      env:
        BUILD_ARTIFACTSTAGINGDIRECTORY: ${CIRRUS_WORKING_DIR}/artifacts
        ARTDIR: ${CIRRUS_WORKING_DIR}/artifacts/
        CI_HAS_ARTIFACTS: true

